import { Product } from "@/types/product";

export const mockProducts: Product[] = [
  // KITCHEN TAPS
  {
    id: "kt-1",
    slug: "deco-claridge-aged-bronze-traditional-pull-out-kitchen-mixer-tap",
    name: "Deco Claridge Aged Bronze Traditional Pull Out Kitchen Mixer Tap",
    sku: "HOC-KT-001",
    category: {
      id: "kitchen",
      name: "Kitchen",
      slug: "kitchen",
    },
    subcategory: "Kitchen Taps",
    description: "Traditional pull-out kitchen mixer tap in aged bronze finish. Features a classic crosshead design with modern functionality.",
    specifications: {
      material: "Solid Brass",
      dimensions: { width: 220, height: 420, depth: 250 },
      weight: 3.2,
      colour: "Aged Bronze",
      finish: "Brushed",
    },
    pricing: {
      price: 397.00,
      priceExVat: 330.83,
    },
    variants: [
      { id: "kt-1-gold", name: "Aged Bronze", sku: "HOC-KT-001-AB", price: 397.00, priceExVat: 330.83, stock: 10, attributes: { colour: "Aged Bronze", colourHex: "#CD7F32" } },
      { id: "kt-1-black", name: "Matte Black", sku: "HOC-KT-001-MB", price: 397.00, priceExVat: 330.83, stock: 8, attributes: { colour: "Matte Black", colourHex: "#1A1A1A" } },
      { id: "kt-1-bronze", name: "Oil Rubbed Bronze", sku: "HOC-KT-001-ORB", price: 397.00, priceExVat: 330.83, stock: 5, attributes: { colour: "Oil Rubbed Bronze", colourHex: "#3D2B1F" } },
      { id: "kt-1-chrome", name: "Chrome", sku: "HOC-KT-001-CR", price: 397.00, priceExVat: 330.83, stock: 15, attributes: { colour: "Chrome", colourHex: "#C0C0C0" } },
      { id: "kt-1-nickel", name: "Brushed Nickel", sku: "HOC-KT-001-BN", price: 397.00, priceExVat: 330.83, stock: 12, attributes: { colour: "Brushed Nickel", colourHex: "#848789" } },
    ],
    images: [
      { id: "kt-1-1", url: "https://images.unsplash.com/photo-1585412459212-4e19768e79fe?w=800&h=1000&fit=crop", alt: "Deco Claridge Kitchen Tap", width: 800, height: 1000 },
      { id: "kt-1-2", url: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&h=1000&fit=crop", alt: "Deco Claridge Kitchen Tap Detail", width: 800, height: 1000 },
    ],
    relatedProducts: ["kt-2", "kt-3"],
    tags: ["kitchen", "tap", "traditional", "bronze"],
    stock: 10,
    isNew: false,
    isFeatured: true,
    deliveryInfo: "Delivery within 7-10 working days",
  },
  {
    id: "kt-2",
    slug: "lambeth-single-hole-traditional-kitchen-tap-aged-bronze",
    name: "Lambeth Single Hole Traditional Kitchen Tap Aged Bronze",
    sku: "HOC-KT-002",
    category: {
      id: "kitchen",
      name: "Kitchen",
      slug: "kitchen",
    },
    subcategory: "Kitchen Taps",
    description: "Elegant single hole traditional kitchen tap with crosshead handles. Perfect for period properties.",
    specifications: {
      material: "Solid Brass",
      dimensions: { width: 180, height: 380, depth: 200 },
      weight: 2.8,
      colour: "Aged Bronze",
      finish: "Brushed",
    },
    pricing: {
      price: 237.00,
      priceExVat: 197.50,
    },
    variants: [
      { id: "kt-2-gold", name: "Aged Bronze", sku: "HOC-KT-002-AB", price: 237.00, priceExVat: 197.50, stock: 10, attributes: { colour: "Aged Bronze", colourHex: "#CD7F32" } },
      { id: "kt-2-black", name: "Matte Black", sku: "HOC-KT-002-MB", price: 237.00, priceExVat: 197.50, stock: 8, attributes: { colour: "Matte Black", colourHex: "#1A1A1A" } },
      { id: "kt-2-chrome", name: "Chrome", sku: "HOC-KT-002-CR", price: 237.00, priceExVat: 197.50, stock: 15, attributes: { colour: "Chrome", colourHex: "#C0C0C0" } },
      { id: "kt-2-nickel", name: "Brushed Nickel", sku: "HOC-KT-002-BN", price: 237.00, priceExVat: 197.50, stock: 12, attributes: { colour: "Brushed Nickel", colourHex: "#848789" } },
      { id: "kt-2-pewter", name: "Pewter", sku: "HOC-KT-002-PW", price: 237.00, priceExVat: 197.50, stock: 6, attributes: { colour: "Pewter", colourHex: "#8A8D8F" } },
    ],
    images: [
      { id: "kt-2-1", url: "https://images.unsplash.com/photo-1585412459212-4e19768e79fe?w=800&h=1000&fit=crop", alt: "Lambeth Kitchen Tap", width: 800, height: 1000 },
    ],
    relatedProducts: ["kt-1", "kt-3"],
    tags: ["kitchen", "tap", "traditional", "bronze"],
    stock: 10,
    isNew: false,
    isFeatured: true,
    deliveryInfo: "Delivery within 7-10 working days",
  },
  {
    id: "kt-3",
    slug: "asbury-4-hole-traditional-kitchen-tap-aged-bronze",
    name: "Asbury 4-Hole Traditional Kitchen Tap Aged Bronze",
    sku: "HOC-KT-003",
    category: {
      id: "kitchen",
      name: "Kitchen",
      slug: "kitchen",
    },
    subcategory: "Kitchen Taps",
    description: "Classic 4-hole kitchen tap with bridge design. Features separate hot and cold controls.",
    specifications: {
      material: "Solid Brass",
      dimensions: { width: 280, height: 350, depth: 220 },
      weight: 4.5,
      colour: "Aged Bronze",
      finish: "Brushed",
    },
    pricing: {
      price: 397.00,
      priceExVat: 330.83,
    },
    variants: [
      { id: "kt-3-gold", name: "Aged Bronze", sku: "HOC-KT-003-AB", price: 397.00, priceExVat: 330.83, stock: 8, attributes: { colour: "Aged Bronze", colourHex: "#CD7F32" } },
      { id: "kt-3-black", name: "Matte Black", sku: "HOC-KT-003-MB", price: 397.00, priceExVat: 330.83, stock: 6, attributes: { colour: "Matte Black", colourHex: "#1A1A1A" } },
      { id: "kt-3-chrome", name: "Chrome", sku: "HOC-KT-003-CR", price: 397.00, priceExVat: 330.83, stock: 10, attributes: { colour: "Chrome", colourHex: "#C0C0C0" } },
      { id: "kt-3-pewter", name: "Pewter", sku: "HOC-KT-003-PW", price: 397.00, priceExVat: 330.83, stock: 4, attributes: { colour: "Pewter", colourHex: "#8A8D8F" } },
    ],
    images: [
      { id: "kt-3-1", url: "https://images.unsplash.com/photo-1585412459212-4e19768e79fe?w=800&h=1000&fit=crop", alt: "Asbury Kitchen Tap", width: 800, height: 1000 },
    ],
    relatedProducts: ["kt-1", "kt-2"],
    tags: ["kitchen", "tap", "traditional", "bronze", "4-hole"],
    stock: 8,
    isNew: false,
    isFeatured: true,
    deliveryInfo: "Delivery within 7-10 working days",
  },
  {
    id: "kt-4",
    slug: "grantley-3-hole-traditional-kitchen-tap-aged-bronze",
    name: "Grantley 3-Hole Traditional Kitchen Tap Aged Bronze",
    sku: "HOC-KT-004",
    category: {
      id: "kitchen",
      name: "Kitchen",
      slug: "kitchen",
    },
    subcategory: "Kitchen Taps",
    description: "Traditional 3-hole kitchen tap with lever handles. Timeless design for any kitchen.",
    specifications: {
      material: "Solid Brass",
      dimensions: { width: 250, height: 380, depth: 200 },
      weight: 3.8,
      colour: "Aged Bronze",
      finish: "Brushed",
    },
    pricing: {
      price: 337.00,
      priceExVat: 280.83,
    },
    variants: [
      { id: "kt-4-gold", name: "Aged Bronze", sku: "HOC-KT-004-AB", price: 337.00, priceExVat: 280.83, stock: 10, attributes: { colour: "Aged Bronze", colourHex: "#CD7F32" } },
      { id: "kt-4-black", name: "Matte Black", sku: "HOC-KT-004-MB", price: 337.00, priceExVat: 280.83, stock: 8, attributes: { colour: "Matte Black", colourHex: "#1A1A1A" } },
      { id: "kt-4-chrome", name: "Chrome", sku: "HOC-KT-004-CR", price: 337.00, priceExVat: 280.83, stock: 12, attributes: { colour: "Chrome", colourHex: "#C0C0C0" } },
      { id: "kt-4-nickel", name: "Brushed Nickel", sku: "HOC-KT-004-BN", price: 337.00, priceExVat: 280.83, stock: 10, attributes: { colour: "Brushed Nickel", colourHex: "#848789" } },
      { id: "kt-4-pewter", name: "Pewter", sku: "HOC-KT-004-PW", price: 337.00, priceExVat: 280.83, stock: 5, attributes: { colour: "Pewter", colourHex: "#8A8D8F" } },
    ],
    images: [
      { id: "kt-4-1", url: "https://images.unsplash.com/photo-1585412459212-4e19768e79fe?w=800&h=1000&fit=crop", alt: "Grantley Kitchen Tap", width: 800, height: 1000 },
    ],
    relatedProducts: ["kt-1", "kt-2"],
    tags: ["kitchen", "tap", "traditional", "bronze", "3-hole"],
    stock: 10,
    isNew: false,
    isFeatured: true,
    deliveryInfo: "Delivery within 7-10 working days",
  },
  // KITCHEN SINKS
  {
    id: "ks-1",
    slug: "belfast-ceramic-sink-white",
    name: "Traditional Belfast Ceramic Kitchen Sink",
    sku: "HOC-KS-001",
    category: {
      id: "kitchen",
      name: "Kitchen",
      slug: "kitchen",
    },
    subcategory: "Kitchen Sinks",
    description: "Classic Belfast sink in premium white ceramic. Deep bowl design perfect for traditional kitchens.",
    specifications: {
      material: "Ceramic",
      dimensions: { width: 595, height: 255, depth: 460 },
      weight: 28,
      colour: "White",
      finish: "Gloss",
    },
    pricing: {
      price: 449.00,
      priceExVat: 374.17,
    },
    variants: [],
    images: [
      { id: "ks-1-1", url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=1000&fit=crop", alt: "Belfast Ceramic Sink", width: 800, height: 1000 },
    ],
    relatedProducts: ["kt-1", "kt-2"],
    tags: ["kitchen", "sink", "ceramic", "belfast"],
    stock: 15,
    isNew: true,
    isFeatured: true,
    deliveryInfo: "Delivery within 10-14 working days",
  },
  // BATHROOM PRODUCTS
  {
    id: "bv-1",
    slug: "hampton-natural-oak-vanity-800mm",
    name: "Hampton Natural Oak Floorstanding Vanity Unit 800mm",
    sku: "HOC-VAN-001",
    category: {
      id: "bathroom",
      name: "Bathroom",
      slug: "bathroom",
    },
    subcategory: "Vanity Units",
    description: "Handcrafted vanity unit combining natural oak with contemporary design. Features soft-close drawers and integrated basin.",
    specifications: {
      material: "Natural Oak",
      dimensions: { width: 800, height: 850, depth: 500 },
      weight: 45,
      colour: "Natural Oak",
      finish: "Matt Lacquer",
    },
    pricing: {
      price: 1897.00,
      priceExVat: 1580.83,
    },
    variants: [],
    images: [
      { id: "bv-1-1", url: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&h=1000&fit=crop", alt: "Hampton Natural Oak Vanity Unit", width: 800, height: 1000 },
      { id: "bv-1-2", url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=1000&fit=crop", alt: "Hampton Vanity Detail", width: 800, height: 1000 },
    ],
    relatedProducts: ["bb-1"],
    tags: ["bathroom", "vanity", "oak", "contemporary"],
    stock: 5,
    isNew: true,
    isFeatured: true,
    deliveryInfo: "Delivery within 14-21 working days",
  },
  {
    id: "bb-1",
    slug: "freestanding-stone-bath-1700mm",
    name: "Freestanding Stone Resin Bath 1700mm",
    sku: "HOC-BTH-001",
    category: {
      id: "bathroom",
      name: "Bathroom",
      slug: "bathroom",
    },
    subcategory: "Baths",
    description: "Luxurious freestanding bath crafted from premium stone resin. Excellent heat retention.",
    specifications: {
      material: "Stone Resin",
      dimensions: { width: 1700, height: 580, depth: 750 },
      weight: 85,
      colour: "White",
      finish: "Matt",
    },
    pricing: {
      price: 2495.00,
      priceExVat: 2079.17,
    },
    variants: [],
    images: [
      { id: "bb-1-1", url: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&h=1000&fit=crop", alt: "Freestanding Stone Bath", width: 800, height: 1000 },
    ],
    relatedProducts: ["bv-1"],
    tags: ["bathroom", "bath", "stone", "freestanding"],
    stock: 3,
    isNew: false,
    isFeatured: true,
    deliveryInfo: "Delivery within 14-21 working days",
  },
  // TILING
  {
    id: "tl-1",
    slug: "calacatta-gold-marble-tile",
    name: "Calacatta Gold Marble Tile 600x600mm",
    sku: "HOC-TIL-001",
    category: {
      id: "tiling",
      name: "Tiling",
      slug: "tiling",
    },
    subcategory: "Marble Tiles",
    description: "Premium Calacatta Gold marble tiles. Each tile is hand-selected for its unique veining pattern.",
    specifications: {
      material: "Natural Marble",
      dimensions: { width: 600, height: 600, depth: 12 },
      colour: "White with Gold Veining",
      finish: "Polished",
    },
    pricing: {
      price: 129.50,
      priceExVat: 107.92,
    },
    variants: [],
    images: [
      { id: "tl-1-1", url: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=800&h=1000&fit=crop", alt: "Calacatta Gold Marble Tile", width: 800, height: 1000 },
    ],
    relatedProducts: [],
    tags: ["tiles", "marble", "calacatta", "luxury"],
    stock: 200,
    isNew: false,
    isFeatured: true,
    deliveryInfo: "Delivery within 7-10 working days",
  },
  // LIGHTING
  {
    id: "lt-1",
    slug: "brass-pendant-light-glass-shade",
    name: "Brass Pendant Light with Glass Shade",
    sku: "HOC-LIT-001",
    category: {
      id: "lighting",
      name: "Lighting",
      slug: "lighting",
    },
    subcategory: "Pendant Lights",
    description: "Elegant brass pendant light with hand-blown glass shade. Perfect for kitchen islands and dining areas.",
    specifications: {
      material: "Brass, Glass",
      dimensions: { width: 300, height: 500, depth: 300 },
      colour: "Brass",
      finish: "Polished",
    },
    pricing: {
      price: 425.00,
      priceExVat: 354.17,
    },
    variants: [],
    images: [
      { id: "lt-1-1", url: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800&h=1000&fit=crop", alt: "Brass Pendant Light", width: 800, height: 1000 },
    ],
    relatedProducts: [],
    tags: ["lighting", "pendant", "brass", "glass"],
    stock: 12,
    isNew: true,
    isFeatured: true,
    deliveryInfo: "Delivery within 10-14 working days",
  },
  // FURNITURE
  {
    id: "fr-1",
    slug: "oak-dining-table-2400mm",
    name: "Solid Oak Dining Table 2400mm",
    sku: "HOC-FRN-001",
    category: {
      id: "furniture",
      name: "Furniture",
      slug: "furniture",
    },
    subcategory: "Dining Room Furniture",
    description: "Handcrafted solid oak dining table with live edge detail. Seats 8-10 people comfortably.",
    specifications: {
      material: "Solid Oak",
      dimensions: { width: 2400, height: 760, depth: 1000 },
      weight: 120,
      colour: "Natural Oak",
      finish: "Oil",
    },
    pricing: {
      price: 3495.00,
      priceExVat: 2912.50,
    },
    variants: [],
    images: [
      { id: "fr-1-1", url: "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&h=1000&fit=crop", alt: "Oak Dining Table", width: 800, height: 1000 },
    ],
    relatedProducts: [],
    tags: ["furniture", "dining", "table", "oak"],
    stock: 2,
    isNew: false,
    isFeatured: true,
    deliveryInfo: "Delivery within 21-28 working days",
  },
  // ELECTRICAL
  {
    id: "el-1",
    slug: "brass-toggle-switch-1-gang",
    name: "Solid Brass Toggle Switch 1 Gang",
    sku: "HOC-ELC-001",
    category: {
      id: "electrical",
      name: "Electrical",
      slug: "electrical",
    },
    subcategory: "Switches",
    description: "Premium solid brass toggle switch with satin finish. British made with 20 year warranty.",
    specifications: {
      material: "Solid Brass",
      dimensions: { width: 86, height: 86, depth: 28 },
      colour: "Satin Brass",
      finish: "Satin",
    },
    pricing: {
      price: 89.00,
      priceExVat: 74.17,
    },
    variants: [
      { id: "el-1-brass", name: "Satin Brass", sku: "HOC-ELC-001-SB", price: 89.00, priceExVat: 74.17, stock: 50, attributes: { colour: "Satin Brass", colourHex: "#D4AF37" } },
      { id: "el-1-black", name: "Matte Black", sku: "HOC-ELC-001-MB", price: 89.00, priceExVat: 74.17, stock: 40, attributes: { colour: "Matte Black", colourHex: "#1A1A1A" } },
      { id: "el-1-chrome", name: "Polished Chrome", sku: "HOC-ELC-001-PC", price: 89.00, priceExVat: 74.17, stock: 60, attributes: { colour: "Polished Chrome", colourHex: "#C0C0C0" } },
      { id: "el-1-nickel", name: "Satin Nickel", sku: "HOC-ELC-001-SN", price: 89.00, priceExVat: 74.17, stock: 35, attributes: { colour: "Satin Nickel", colourHex: "#848789" } },
    ],
    images: [
      { id: "el-1-1", url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=1000&fit=crop", alt: "Brass Toggle Switch", width: 800, height: 1000 },
    ],
    relatedProducts: [],
    tags: ["electrical", "switch", "brass", "toggle"],
    stock: 50,
    isNew: false,
    isFeatured: true,
    deliveryInfo: "Delivery within 3-5 working days",
  },
];

export const featuredProducts = mockProducts.filter((p) => p.isFeatured);
