import { Product, Category } from "@/types/product";

export const mockProducts: Product[] = [
  {
    id: "1",
    slug: "hampton-natural-oak-vanity-800mm",
    name: "Hampton Natural Oak Floorstanding Vanity Unit 800mm",
    sku: "HOC-VAN-001",
    category: {
      id: "bathroom",
      name: "Bathroom",
      slug: "bathroom",
    },
    subcategory: "Vanity Units",
    description: "Handcrafted vanity unit combining natural oak with contemporary design. Features soft-close drawers and integrated basin.",
    specifications: {
      material: "Natural Oak",
      dimensions: { width: 800, height: 850, depth: 500 },
      weight: 45,
      colour: "Natural Oak",
      finish: "Matt Lacquer",
    },
    pricing: {
      price: 1897.00,
      priceExVat: 1580.83,
    },
    variants: [],
    images: [
      {
        id: "1",
        url: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&h=1000&fit=crop",
        alt: "Hampton Natural Oak Vanity Unit",
        width: 800,
        height: 1000,
      },
    ],
    relatedProducts: [],
    tags: ["bathroom", "vanity", "oak", "contemporary"],
    stock: 5,
    isNew: true,
    isFeatured: true,
    deliveryInfo: "Delivery within 14-21 working days",
  },
  {
    id: "2",
    slug: "marble-mosaic-tile-collection",
    name: "Calacatta Gold Marble Mosaic Tile",
    sku: "HOC-TIL-002",
    category: {
      id: "tiles",
      name: "Tiles",
      slug: "tiles",
    },
    subcategory: "Mosaic",
    description: "Premium Calacatta Gold marble mosaic tiles. Each tile is hand-selected for its unique veining pattern.",
    specifications: {
      material: "Natural Marble",
      dimensions: { width: 300, height: 300, depth: 10 },
      colour: "White with Gold Veining",
      finish: "Polished",
    },
    pricing: {
      price: 129.50,
      priceExVat: 107.92,
    },
    variants: [],
    images: [
      {
        id: "2",
        url: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=800&h=1000&fit=crop",
        alt: "Calacatta Gold Marble Mosaic Tile",
        width: 800,
        height: 1000,
      },
    ],
    relatedProducts: [],
    tags: ["tiles", "marble", "mosaic", "luxury"],
    stock: 50,
    isNew: false,
    isFeatured: true,
    deliveryInfo: "Delivery within 7-10 working days",
  },
  {
    id: "3",
    slug: "brass-pendant-light",
    name: "Brass Pendant Light with Glass Shade",
    sku: "HOC-LIT-003",
    category: {
      id: "lighting",
      name: "Lighting",
      slug: "lighting",
    },
    subcategory: "Pendant",
    description: "Elegant brass pendant light with hand-blown glass shade. Perfect for kitchen islands and dining areas.",
    specifications: {
      material: "Brass, Glass",
      dimensions: { width: 300, height: 500, depth: 300 },
      colour: "Brass",
      finish: "Polished",
    },
    pricing: {
      price: 425.00,
      priceExVat: 354.17,
    },
    variants: [],
    images: [
      {
        id: "3",
        url: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800&h=1000&fit=crop",
        alt: "Brass Pendant Light",
        width: 800,
        height: 1000,
      },
    ],
    relatedProducts: [],
    tags: ["lighting", "pendant", "brass", "kitchen"],
    stock: 12,
    isNew: false,
    isFeatured: true,
    deliveryInfo: "Delivery within 10-14 working days",
  },
  {
    id: "4",
    slug: "designer-radiator-vertical",
    name: "Designer Vertical Radiator 1800mm",
    sku: "HOC-HEA-004",
    category: {
      id: "heating",
      name: "Heating",
      slug: "heating",
    },
    subcategory: "Designer Radiators",
    description: "Sleek vertical designer radiator in matte black finish. Perfect for modern interiors.",
    specifications: {
      material: "Steel",
      dimensions: { width: 500, height: 1800, depth: 100 },
      colour: "Matte Black",
      finish: "Powder Coated",
    },
    pricing: {
      price: 675.00,
      priceExVat: 562.50,
    },
    variants: [],
    images: [
      {
        id: "4",
        url: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&h=1000&fit=crop",
        alt: "Designer Vertical Radiator",
        width: 800,
        height: 1000,
      },
    ],
    relatedProducts: [],
    tags: ["heating", "radiator", "designer"],
    stock: 8,
    isNew: false,
    isFeatured: false,
    deliveryInfo: "Delivery within 10-14 working days",
  },
  {
    id: "5",
    slug: "ceramic-basin-wall-mounted",
    name: "Wall-Mounted Ceramic Basin 600mm",
    sku: "HOC-BAT-005",
    category: {
      id: "bathroom",
      name: "Bathroom",
      slug: "bathroom",
    },
    subcategory: "Basins",
    description: "Minimalist wall-mounted ceramic basin with clean lines. Available in white or black.",
    specifications: {
      material: "Ceramic",
      dimensions: { width: 600, height: 150, depth: 400 },
      colour: "White",
      finish: "Gloss",
    },
    pricing: {
      price: 285.00,
      priceExVat: 237.50,
    },
    variants: [
      {
        id: "5-black",
        name: "Black",
        sku: "HOC-BAT-005-BLK",
        price: 285.00,
        priceExVat: 237.50,
        stock: 15,
        attributes: { colour: "Black" },
      },
    ],
    images: [
      {
        id: "5",
        url: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=1000&fit=crop",
        alt: "Wall-Mounted Ceramic Basin",
        width: 800,
        height: 1000,
      },
    ],
    relatedProducts: [],
    tags: ["bathroom", "basin", "ceramic"],
    stock: 20,
    isNew: true,
    isFeatured: false,
    deliveryInfo: "Delivery within 7-10 working days",
  },
];

export const featuredProducts = mockProducts.filter((p) => p.isFeatured);
